[2022-10-15 12:20:41,659] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:20:41,670] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:20:41,673] {logging_mixin.py:115} INFO - [2022-10-15 12:20:41,673] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:20:41,704] {logging_mixin.py:115} INFO - [2022-10-15 12:20:41,702] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:20:41,706] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:20:41,786] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.134 seconds
[2022-10-15 12:21:12,322] {processor.py:153} INFO - Started process (PID=101) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:21:12,325] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:21:12,326] {logging_mixin.py:115} INFO - [2022-10-15 12:21:12,326] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:21:12,341] {logging_mixin.py:115} INFO - [2022-10-15 12:21:12,338] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:21:12,343] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:21:12,368] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.053 seconds
[2022-10-15 12:21:43,003] {processor.py:153} INFO - Started process (PID=168) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:21:43,006] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:21:43,009] {logging_mixin.py:115} INFO - [2022-10-15 12:21:43,009] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:21:43,025] {logging_mixin.py:115} INFO - [2022-10-15 12:21:43,017] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:21:43,028] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:21:43,055] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.064 seconds
[2022-10-15 12:22:13,753] {processor.py:153} INFO - Started process (PID=226) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:22:13,755] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:22:13,759] {logging_mixin.py:115} INFO - [2022-10-15 12:22:13,759] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:22:13,770] {logging_mixin.py:115} INFO - [2022-10-15 12:22:13,768] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:22:13,771] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:22:13,789] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.043 seconds
[2022-10-15 12:22:44,206] {processor.py:153} INFO - Started process (PID=292) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:22:44,208] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:22:44,209] {logging_mixin.py:115} INFO - [2022-10-15 12:22:44,209] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:22:44,218] {logging_mixin.py:115} INFO - [2022-10-15 12:22:44,214] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:22:44,219] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:22:44,250] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.049 seconds
[2022-10-15 12:23:14,816] {processor.py:153} INFO - Started process (PID=359) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:23:14,819] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:23:14,821] {logging_mixin.py:115} INFO - [2022-10-15 12:23:14,821] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:23:14,833] {logging_mixin.py:115} INFO - [2022-10-15 12:23:14,830] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:23:14,834] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:23:14,860] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.053 seconds
[2022-10-15 12:23:45,639] {processor.py:153} INFO - Started process (PID=426) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:23:45,641] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:23:45,643] {logging_mixin.py:115} INFO - [2022-10-15 12:23:45,643] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:23:45,653] {logging_mixin.py:115} INFO - [2022-10-15 12:23:45,650] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:23:45,656] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:23:45,681] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.053 seconds
[2022-10-15 12:24:16,382] {processor.py:153} INFO - Started process (PID=493) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:24:16,384] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:24:16,386] {logging_mixin.py:115} INFO - [2022-10-15 12:24:16,386] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:24:16,393] {logging_mixin.py:115} INFO - [2022-10-15 12:24:16,391] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:24:16,394] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:24:16,422] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.048 seconds
[2022-10-15 12:24:46,491] {processor.py:153} INFO - Started process (PID=560) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:24:46,492] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:24:46,494] {logging_mixin.py:115} INFO - [2022-10-15 12:24:46,493] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:24:46,500] {logging_mixin.py:115} INFO - [2022-10-15 12:24:46,498] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:24:46,501] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:24:46,526] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.040 seconds
[2022-10-15 12:25:17,044] {processor.py:153} INFO - Started process (PID=618) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:25:17,046] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:25:17,049] {logging_mixin.py:115} INFO - [2022-10-15 12:25:17,048] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:25:17,058] {logging_mixin.py:115} INFO - [2022-10-15 12:25:17,056] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:25:17,060] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:25:17,082] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.045 seconds
[2022-10-15 12:25:47,512] {processor.py:153} INFO - Started process (PID=686) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:25:47,514] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:25:47,515] {logging_mixin.py:115} INFO - [2022-10-15 12:25:47,515] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:25:47,528] {logging_mixin.py:115} INFO - [2022-10-15 12:25:47,524] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:25:47,529] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:25:47,555] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.049 seconds
[2022-10-15 12:26:17,791] {processor.py:153} INFO - Started process (PID=752) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:26:17,794] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:26:17,796] {logging_mixin.py:115} INFO - [2022-10-15 12:26:17,796] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:26:17,809] {logging_mixin.py:115} INFO - [2022-10-15 12:26:17,806] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:26:17,810] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:26:17,850] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.066 seconds
[2022-10-15 12:26:48,010] {processor.py:153} INFO - Started process (PID=819) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:26:48,011] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:26:48,012] {logging_mixin.py:115} INFO - [2022-10-15 12:26:48,012] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:26:48,019] {logging_mixin.py:115} INFO - [2022-10-15 12:26:48,017] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:26:48,021] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:26:48,040] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.035 seconds
[2022-10-15 12:27:18,229] {processor.py:153} INFO - Started process (PID=878) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:27:18,231] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:27:18,233] {logging_mixin.py:115} INFO - [2022-10-15 12:27:18,233] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:27:18,240] {logging_mixin.py:115} INFO - [2022-10-15 12:27:18,238] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:27:18,242] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:27:18,263] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.038 seconds
[2022-10-15 12:27:48,570] {processor.py:153} INFO - Started process (PID=944) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:27:48,571] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:27:48,572] {logging_mixin.py:115} INFO - [2022-10-15 12:27:48,572] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:27:48,582] {logging_mixin.py:115} INFO - [2022-10-15 12:27:48,580] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:27:48,583] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:27:48,615] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.049 seconds
[2022-10-15 12:28:18,744] {processor.py:153} INFO - Started process (PID=1012) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:28:18,749] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:28:18,752] {logging_mixin.py:115} INFO - [2022-10-15 12:28:18,751] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:28:18,769] {logging_mixin.py:115} INFO - [2022-10-15 12:28:18,766] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:28:18,770] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:28:18,856] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.120 seconds
[2022-10-15 12:28:49,223] {processor.py:153} INFO - Started process (PID=1079) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:28:49,230] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:28:49,234] {logging_mixin.py:115} INFO - [2022-10-15 12:28:49,234] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:28:49,258] {logging_mixin.py:115} INFO - [2022-10-15 12:28:49,250] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:28:49,259] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:28:49,320] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.117 seconds
[2022-10-15 12:29:19,812] {processor.py:153} INFO - Started process (PID=1145) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:29:19,828] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:29:19,832] {logging_mixin.py:115} INFO - [2022-10-15 12:29:19,832] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:29:19,863] {logging_mixin.py:115} INFO - [2022-10-15 12:29:19,856] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:29:19,867] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:29:19,927] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.137 seconds
[2022-10-15 12:29:50,623] {processor.py:153} INFO - Started process (PID=1203) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:29:50,627] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:29:50,629] {logging_mixin.py:115} INFO - [2022-10-15 12:29:50,629] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:29:50,644] {logging_mixin.py:115} INFO - [2022-10-15 12:29:50,641] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:29:50,645] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:29:50,705] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.088 seconds
[2022-10-15 12:30:21,587] {processor.py:153} INFO - Started process (PID=1272) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:30:21,589] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:30:21,590] {logging_mixin.py:115} INFO - [2022-10-15 12:30:21,590] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:30:21,604] {logging_mixin.py:115} INFO - [2022-10-15 12:30:21,602] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:30:21,605] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:30:21,641] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.062 seconds
[2022-10-15 12:30:51,763] {processor.py:153} INFO - Started process (PID=1340) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:30:51,766] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:30:51,767] {logging_mixin.py:115} INFO - [2022-10-15 12:30:51,767] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:30:51,777] {logging_mixin.py:115} INFO - [2022-10-15 12:30:51,775] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:30:51,778] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:30:51,803] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.047 seconds
[2022-10-15 12:31:21,907] {processor.py:153} INFO - Started process (PID=1398) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:31:21,910] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:31:21,911] {logging_mixin.py:115} INFO - [2022-10-15 12:31:21,911] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:31:21,926] {logging_mixin.py:115} INFO - [2022-10-15 12:31:21,924] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:31:21,927] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:31:21,947] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.047 seconds
[2022-10-15 12:31:52,442] {processor.py:153} INFO - Started process (PID=1466) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:31:52,444] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:31:52,445] {logging_mixin.py:115} INFO - [2022-10-15 12:31:52,445] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:31:52,454] {logging_mixin.py:115} INFO - [2022-10-15 12:31:52,450] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:31:52,457] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:31:52,494] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.060 seconds
[2022-10-15 12:32:22,634] {processor.py:153} INFO - Started process (PID=1533) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:32:22,636] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:32:22,638] {logging_mixin.py:115} INFO - [2022-10-15 12:32:22,638] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:32:22,653] {logging_mixin.py:115} INFO - [2022-10-15 12:32:22,646] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:32:22,654] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:32:22,684] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.060 seconds
[2022-10-15 12:32:52,889] {processor.py:153} INFO - Started process (PID=1600) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:32:52,900] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:32:52,904] {logging_mixin.py:115} INFO - [2022-10-15 12:32:52,904] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:32:52,916] {logging_mixin.py:115} INFO - [2022-10-15 12:32:52,914] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:32:52,917] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:32:52,946] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.065 seconds
[2022-10-15 12:33:22,994] {processor.py:153} INFO - Started process (PID=1657) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:33:22,996] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:33:22,997] {logging_mixin.py:115} INFO - [2022-10-15 12:33:22,997] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:33:23,005] {logging_mixin.py:115} INFO - [2022-10-15 12:33:23,003] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:33:23,006] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:33:23,038] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.051 seconds
[2022-10-15 12:33:53,739] {processor.py:153} INFO - Started process (PID=1724) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:33:53,742] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:33:53,744] {logging_mixin.py:115} INFO - [2022-10-15 12:33:53,744] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:33:53,751] {logging_mixin.py:115} INFO - [2022-10-15 12:33:53,749] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:33:53,752] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:33:53,784] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.049 seconds
[2022-10-15 12:34:23,889] {processor.py:153} INFO - Started process (PID=1791) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:34:23,893] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:34:23,895] {logging_mixin.py:115} INFO - [2022-10-15 12:34:23,895] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:34:23,907] {logging_mixin.py:115} INFO - [2022-10-15 12:34:23,905] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:34:23,908] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:34:23,963] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.086 seconds
[2022-10-15 12:34:54,125] {processor.py:153} INFO - Started process (PID=1849) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:34:54,129] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:34:54,130] {logging_mixin.py:115} INFO - [2022-10-15 12:34:54,130] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:34:54,146] {logging_mixin.py:115} INFO - [2022-10-15 12:34:54,141] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:34:54,149] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:34:54,212] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.091 seconds
[2022-10-15 12:35:24,557] {processor.py:153} INFO - Started process (PID=1916) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:35:24,566] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:35:24,576] {logging_mixin.py:115} INFO - [2022-10-15 12:35:24,576] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:35:24,600] {logging_mixin.py:115} INFO - [2022-10-15 12:35:24,594] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:35:24,601] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:35:24,652] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.104 seconds
[2022-10-15 12:35:55,001] {processor.py:153} INFO - Started process (PID=1983) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:35:55,004] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:35:55,005] {logging_mixin.py:115} INFO - [2022-10-15 12:35:55,005] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:35:55,011] {logging_mixin.py:115} INFO - [2022-10-15 12:35:55,010] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:35:55,012] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:35:55,028] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.030 seconds
[2022-10-15 12:36:25,933] {processor.py:153} INFO - Started process (PID=2050) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:36:25,935] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:36:25,937] {logging_mixin.py:115} INFO - [2022-10-15 12:36:25,937] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:36:25,945] {logging_mixin.py:115} INFO - [2022-10-15 12:36:25,943] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:36:25,946] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:36:25,965] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.041 seconds
[2022-10-15 12:36:56,072] {processor.py:153} INFO - Started process (PID=2118) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:36:56,075] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:36:56,077] {logging_mixin.py:115} INFO - [2022-10-15 12:36:56,077] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:36:56,085] {logging_mixin.py:115} INFO - [2022-10-15 12:36:56,084] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:36:56,087] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:36:56,122] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.059 seconds
[2022-10-15 12:37:26,363] {processor.py:153} INFO - Started process (PID=2176) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:37:26,365] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:37:26,366] {logging_mixin.py:115} INFO - [2022-10-15 12:37:26,366] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:37:26,375] {logging_mixin.py:115} INFO - [2022-10-15 12:37:26,373] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:37:26,376] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:37:26,406] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.046 seconds
[2022-10-15 12:37:56,784] {processor.py:153} INFO - Started process (PID=2243) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:37:56,786] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:37:56,787] {logging_mixin.py:115} INFO - [2022-10-15 12:37:56,787] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:37:56,795] {logging_mixin.py:115} INFO - [2022-10-15 12:37:56,793] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:37:56,796] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:37:56,826] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.046 seconds
[2022-10-15 12:38:27,022] {processor.py:153} INFO - Started process (PID=2309) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:38:27,027] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:38:27,029] {logging_mixin.py:115} INFO - [2022-10-15 12:38:27,029] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:38:27,037] {logging_mixin.py:115} INFO - [2022-10-15 12:38:27,035] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:38:27,040] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:38:27,080] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.063 seconds
[2022-10-15 12:38:57,386] {processor.py:153} INFO - Started process (PID=2367) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:38:57,391] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:38:57,395] {logging_mixin.py:115} INFO - [2022-10-15 12:38:57,395] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:38:57,407] {logging_mixin.py:115} INFO - [2022-10-15 12:38:57,404] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:38:57,409] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:38:57,438] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.057 seconds
[2022-10-15 12:39:28,385] {processor.py:153} INFO - Started process (PID=2435) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:39:28,387] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:39:28,389] {logging_mixin.py:115} INFO - [2022-10-15 12:39:28,389] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:39:28,397] {logging_mixin.py:115} INFO - [2022-10-15 12:39:28,395] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:39:28,398] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:39:28,425] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.047 seconds
[2022-10-15 12:39:58,955] {processor.py:153} INFO - Started process (PID=2501) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:39:58,957] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:39:58,959] {logging_mixin.py:115} INFO - [2022-10-15 12:39:58,959] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:39:58,968] {logging_mixin.py:115} INFO - [2022-10-15 12:39:58,966] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:39:58,971] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:39:58,998] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.054 seconds
[2022-10-15 12:40:29,411] {processor.py:153} INFO - Started process (PID=2569) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:40:29,413] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:40:29,415] {logging_mixin.py:115} INFO - [2022-10-15 12:40:29,415] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:40:29,427] {logging_mixin.py:115} INFO - [2022-10-15 12:40:29,424] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:40:29,427] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:40:29,452] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.049 seconds
[2022-10-15 12:40:59,778] {processor.py:153} INFO - Started process (PID=2636) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:40:59,780] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:40:59,782] {logging_mixin.py:115} INFO - [2022-10-15 12:40:59,781] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:40:59,796] {logging_mixin.py:115} INFO - [2022-10-15 12:40:59,793] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:40:59,798] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:40:59,836] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.072 seconds
[2022-10-15 12:41:30,600] {processor.py:153} INFO - Started process (PID=2694) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:41:30,603] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:41:30,605] {logging_mixin.py:115} INFO - [2022-10-15 12:41:30,605] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:41:30,616] {logging_mixin.py:115} INFO - [2022-10-15 12:41:30,613] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:41:30,618] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:41:30,655] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.063 seconds
[2022-10-15 12:42:01,001] {processor.py:153} INFO - Started process (PID=2762) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:42:01,003] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:42:01,004] {logging_mixin.py:115} INFO - [2022-10-15 12:42:01,004] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:42:01,015] {logging_mixin.py:115} INFO - [2022-10-15 12:42:01,011] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:42:01,016] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:42:01,047] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.051 seconds
[2022-10-15 12:42:31,594] {processor.py:153} INFO - Started process (PID=2829) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:42:31,597] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:42:31,601] {logging_mixin.py:115} INFO - [2022-10-15 12:42:31,601] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:42:31,616] {logging_mixin.py:115} INFO - [2022-10-15 12:42:31,614] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:42:31,617] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:42:31,645] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.058 seconds
[2022-10-15 12:43:02,008] {processor.py:153} INFO - Started process (PID=2889) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:43:02,011] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:43:02,013] {logging_mixin.py:115} INFO - [2022-10-15 12:43:02,013] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:43:02,023] {logging_mixin.py:115} INFO - [2022-10-15 12:43:02,020] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:43:02,025] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:43:02,058] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.058 seconds
[2022-10-15 12:43:32,097] {processor.py:153} INFO - Started process (PID=2955) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:43:32,099] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:43:32,100] {logging_mixin.py:115} INFO - [2022-10-15 12:43:32,100] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:43:32,108] {logging_mixin.py:115} INFO - [2022-10-15 12:43:32,106] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:43:32,111] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:43:32,132] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.039 seconds
[2022-10-15 12:44:02,483] {processor.py:153} INFO - Started process (PID=3022) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:44:02,485] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:44:02,487] {logging_mixin.py:115} INFO - [2022-10-15 12:44:02,487] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:44:02,495] {logging_mixin.py:115} INFO - [2022-10-15 12:44:02,493] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:44:02,496] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:44:02,515] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.040 seconds
[2022-10-15 12:44:32,703] {processor.py:153} INFO - Started process (PID=3088) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:44:32,704] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:44:32,706] {logging_mixin.py:115} INFO - [2022-10-15 12:44:32,706] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:44:32,712] {logging_mixin.py:115} INFO - [2022-10-15 12:44:32,710] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:44:32,713] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:44:32,736] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.038 seconds
[2022-10-15 12:45:03,013] {processor.py:153} INFO - Started process (PID=3156) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:45:03,015] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:45:03,016] {logging_mixin.py:115} INFO - [2022-10-15 12:45:03,016] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:45:03,032] {logging_mixin.py:115} INFO - [2022-10-15 12:45:03,030] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:45:03,034] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:45:03,056] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.050 seconds
[2022-10-15 12:45:34,029] {processor.py:153} INFO - Started process (PID=3215) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:45:34,032] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:45:34,033] {logging_mixin.py:115} INFO - [2022-10-15 12:45:34,033] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:45:34,042] {logging_mixin.py:115} INFO - [2022-10-15 12:45:34,040] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:45:34,043] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:45:34,068] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.045 seconds
[2022-10-15 12:46:04,535] {processor.py:153} INFO - Started process (PID=3282) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:46:04,537] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:46:04,539] {logging_mixin.py:115} INFO - [2022-10-15 12:46:04,538] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:46:04,548] {logging_mixin.py:115} INFO - [2022-10-15 12:46:04,546] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:46:04,549] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:46:04,578] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.049 seconds
[2022-10-15 12:46:34,910] {processor.py:153} INFO - Started process (PID=3349) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:46:34,912] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:46:34,914] {logging_mixin.py:115} INFO - [2022-10-15 12:46:34,914] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:46:34,925] {logging_mixin.py:115} INFO - [2022-10-15 12:46:34,920] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:46:34,928] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:46:34,955] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.051 seconds
[2022-10-15 12:47:05,600] {processor.py:153} INFO - Started process (PID=3415) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:47:05,601] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:47:05,605] {logging_mixin.py:115} INFO - [2022-10-15 12:47:05,604] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:47:05,613] {logging_mixin.py:115} INFO - [2022-10-15 12:47:05,611] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:47:05,615] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:47:05,633] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.046 seconds
[2022-10-15 12:47:35,776] {processor.py:153} INFO - Started process (PID=3483) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:47:35,779] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:47:35,780] {logging_mixin.py:115} INFO - [2022-10-15 12:47:35,780] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:47:35,788] {logging_mixin.py:115} INFO - [2022-10-15 12:47:35,786] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:47:35,789] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:47:35,828] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.061 seconds
[2022-10-15 12:48:06,158] {processor.py:153} INFO - Started process (PID=3541) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:48:06,162] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:48:06,164] {logging_mixin.py:115} INFO - [2022-10-15 12:48:06,164] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:48:06,175] {logging_mixin.py:115} INFO - [2022-10-15 12:48:06,173] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:48:06,179] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:48:06,215] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.064 seconds
[2022-10-15 12:48:37,019] {processor.py:153} INFO - Started process (PID=3606) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:48:37,021] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:48:37,022] {logging_mixin.py:115} INFO - [2022-10-15 12:48:37,022] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:48:37,029] {logging_mixin.py:115} INFO - [2022-10-15 12:48:37,027] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:48:37,030] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:48:37,062] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.050 seconds
[2022-10-15 12:49:07,385] {processor.py:153} INFO - Started process (PID=3672) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:49:07,388] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:49:07,395] {logging_mixin.py:115} INFO - [2022-10-15 12:49:07,395] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:49:07,417] {logging_mixin.py:115} INFO - [2022-10-15 12:49:07,412] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:49:07,419] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:49:07,452] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.078 seconds
[2022-10-15 12:49:37,616] {processor.py:153} INFO - Started process (PID=3739) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:49:37,618] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:49:37,619] {logging_mixin.py:115} INFO - [2022-10-15 12:49:37,619] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:49:37,626] {logging_mixin.py:115} INFO - [2022-10-15 12:49:37,624] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:49:37,627] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:49:37,645] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.032 seconds
[2022-10-15 12:50:08,005] {processor.py:153} INFO - Started process (PID=3796) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:50:08,006] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:50:08,012] {logging_mixin.py:115} INFO - [2022-10-15 12:50:08,012] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:50:08,020] {logging_mixin.py:115} INFO - [2022-10-15 12:50:08,018] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:50:08,021] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:50:08,053] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.052 seconds
[2022-10-15 12:50:38,214] {processor.py:153} INFO - Started process (PID=3863) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:50:38,216] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:50:38,218] {logging_mixin.py:115} INFO - [2022-10-15 12:50:38,218] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:50:38,227] {logging_mixin.py:115} INFO - [2022-10-15 12:50:38,224] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:50:38,229] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:50:38,247] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.037 seconds
[2022-10-15 12:51:08,845] {processor.py:153} INFO - Started process (PID=3930) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:51:08,848] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:51:08,849] {logging_mixin.py:115} INFO - [2022-10-15 12:51:08,849] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:51:08,864] {logging_mixin.py:115} INFO - [2022-10-15 12:51:08,858] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:51:08,865] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:51:08,885] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.050 seconds
[2022-10-15 12:51:39,571] {processor.py:153} INFO - Started process (PID=3997) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:51:39,575] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:51:39,577] {logging_mixin.py:115} INFO - [2022-10-15 12:51:39,577] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:51:39,585] {logging_mixin.py:115} INFO - [2022-10-15 12:51:39,583] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:51:39,587] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:51:39,606] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.041 seconds
[2022-10-15 12:52:09,879] {processor.py:153} INFO - Started process (PID=4055) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:52:09,882] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:52:09,884] {logging_mixin.py:115} INFO - [2022-10-15 12:52:09,884] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:52:09,895] {logging_mixin.py:115} INFO - [2022-10-15 12:52:09,892] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:52:09,896] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:52:09,930] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.058 seconds
[2022-10-15 12:52:40,118] {processor.py:153} INFO - Started process (PID=4122) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:52:40,120] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:52:40,123] {logging_mixin.py:115} INFO - [2022-10-15 12:52:40,123] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:52:40,133] {logging_mixin.py:115} INFO - [2022-10-15 12:52:40,131] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:52:40,135] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:52:40,157] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.049 seconds
[2022-10-15 12:53:10,542] {processor.py:153} INFO - Started process (PID=4188) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:53:10,545] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:53:10,547] {logging_mixin.py:115} INFO - [2022-10-15 12:53:10,547] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:53:10,559] {logging_mixin.py:115} INFO - [2022-10-15 12:53:10,555] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:53:10,560] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:53:10,582] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.051 seconds
[2022-10-15 12:53:41,126] {processor.py:153} INFO - Started process (PID=4255) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:53:41,128] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:53:41,130] {logging_mixin.py:115} INFO - [2022-10-15 12:53:41,130] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:53:41,140] {logging_mixin.py:115} INFO - [2022-10-15 12:53:41,138] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:53:41,141] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:53:41,163] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.047 seconds
[2022-10-15 12:54:11,247] {processor.py:153} INFO - Started process (PID=4322) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:54:11,249] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:54:11,251] {logging_mixin.py:115} INFO - [2022-10-15 12:54:11,251] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:54:11,270] {logging_mixin.py:115} INFO - [2022-10-15 12:54:11,258] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:54:11,272] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:54:11,296] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.051 seconds
[2022-10-15 12:54:41,477] {processor.py:153} INFO - Started process (PID=4378) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:54:41,480] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:54:41,481] {logging_mixin.py:115} INFO - [2022-10-15 12:54:41,481] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:54:41,492] {logging_mixin.py:115} INFO - [2022-10-15 12:54:41,490] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:54:41,494] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:54:41,514] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.046 seconds
[2022-10-15 12:55:11,962] {processor.py:153} INFO - Started process (PID=4445) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:55:11,964] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:55:11,966] {logging_mixin.py:115} INFO - [2022-10-15 12:55:11,966] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:55:11,976] {logging_mixin.py:115} INFO - [2022-10-15 12:55:11,972] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:55:11,977] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:55:12,002] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.047 seconds
[2022-10-15 12:55:42,290] {processor.py:153} INFO - Started process (PID=4512) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:55:42,292] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:55:42,294] {logging_mixin.py:115} INFO - [2022-10-15 12:55:42,294] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:55:42,305] {logging_mixin.py:115} INFO - [2022-10-15 12:55:42,303] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:55:42,306] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:55:42,328] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.047 seconds
[2022-10-15 12:56:12,454] {processor.py:153} INFO - Started process (PID=4578) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:56:12,456] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:56:12,458] {logging_mixin.py:115} INFO - [2022-10-15 12:56:12,458] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:56:12,464] {logging_mixin.py:115} INFO - [2022-10-15 12:56:12,462] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:56:12,465] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:56:12,481] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.029 seconds
[2022-10-15 12:56:42,826] {processor.py:153} INFO - Started process (PID=4636) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:56:42,828] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:56:42,830] {logging_mixin.py:115} INFO - [2022-10-15 12:56:42,830] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:56:42,841] {logging_mixin.py:115} INFO - [2022-10-15 12:56:42,838] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:56:42,842] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:56:42,873] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.054 seconds
[2022-10-15 12:57:13,555] {processor.py:153} INFO - Started process (PID=4702) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:57:13,557] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:57:13,559] {logging_mixin.py:115} INFO - [2022-10-15 12:57:13,559] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:57:13,584] {logging_mixin.py:115} INFO - [2022-10-15 12:57:13,576] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:57:13,587] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:57:13,650] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.106 seconds
[2022-10-15 12:57:43,844] {processor.py:153} INFO - Started process (PID=4769) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:57:43,847] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:57:43,849] {logging_mixin.py:115} INFO - [2022-10-15 12:57:43,849] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:57:43,864] {logging_mixin.py:115} INFO - [2022-10-15 12:57:43,859] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:57:43,865] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:57:43,893] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.064 seconds
[2022-10-15 12:58:14,484] {processor.py:153} INFO - Started process (PID=4835) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:58:14,487] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:58:14,489] {logging_mixin.py:115} INFO - [2022-10-15 12:58:14,489] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:58:14,515] {logging_mixin.py:115} INFO - [2022-10-15 12:58:14,514] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:58:14,516] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:58:14,549] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.085 seconds
[2022-10-15 12:58:44,969] {processor.py:153} INFO - Started process (PID=4893) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:58:44,972] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:58:44,974] {logging_mixin.py:115} INFO - [2022-10-15 12:58:44,974] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:58:44,984] {logging_mixin.py:115} INFO - [2022-10-15 12:58:44,981] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:58:44,986] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:58:45,018] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.058 seconds
[2022-10-15 12:59:15,656] {processor.py:153} INFO - Started process (PID=4959) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:59:15,658] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:59:15,659] {logging_mixin.py:115} INFO - [2022-10-15 12:59:15,659] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:59:15,673] {logging_mixin.py:115} INFO - [2022-10-15 12:59:15,666] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:59:15,674] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:59:15,717] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.074 seconds
[2022-10-15 12:59:46,057] {processor.py:153} INFO - Started process (PID=5025) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 12:59:46,060] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 12:59:46,062] {logging_mixin.py:115} INFO - [2022-10-15 12:59:46,062] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 12:59:46,071] {logging_mixin.py:115} INFO - [2022-10-15 12:59:46,069] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 12:59:46,073] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 12:59:46,098] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.049 seconds
[2022-10-15 13:00:16,656] {processor.py:153} INFO - Started process (PID=5090) to work on /opt/airflow/dags/main_inference.py
[2022-10-15 13:00:16,659] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_inference.py for tasks to queue
[2022-10-15 13:00:16,661] {logging_mixin.py:115} INFO - [2022-10-15 13:00:16,661] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_inference.py
[2022-10-15 13:00:16,675] {logging_mixin.py:115} INFO - [2022-10-15 13:00:16,673] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_inference.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_inference.py", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2022-10-15 13:00:16,677] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_inference.py
[2022-10-15 13:00:16,713] {processor.py:161} INFO - Processing /opt/airflow/dags/main_inference.py took 0.061 seconds
