[2022-09-14 16:35:58,379] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 3_download_rocket_launches.print_stats manual__2022-09-14T16:35:55.400085+00:00 [queued]>
[2022-09-14 16:35:58,385] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 3_download_rocket_launches.print_stats manual__2022-09-14T16:35:55.400085+00:00 [queued]>
[2022-09-14 16:35:58,386] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 16:35:58,387] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-14 16:35:58,387] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 16:35:58,396] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): print_stats> on 2022-09-14 16:35:55.400085+00:00
[2022-09-14 16:35:58,400] {standard_task_runner.py:52} INFO - Started process 645 to run task
[2022-09-14 16:35:58,403] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '3_download_rocket_launches', 'print_stats', 'manual__2022-09-14T16:35:55.400085+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/test_test.py', '--cfg-path', '/tmp/tmp0pc188mv', '--error-file', '/tmp/tmp1y41qbr_']
[2022-09-14 16:35:58,404] {standard_task_runner.py:80} INFO - Job 83: Subtask print_stats
[2022-09-14 16:35:58,438] {task_command.py:369} INFO - Running <TaskInstance: 3_download_rocket_launches.print_stats manual__2022-09-14T16:35:55.400085+00:00 [running]> on host 1085bb4029c2
[2022-09-14 16:35:58,477] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=3_download_rocket_launches
AIRFLOW_CTX_TASK_ID=print_stats
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T16:35:55.400085+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T16:35:55.400085+00:00
[2022-09-14 16:35:58,482] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_test.py", line 44, in _print_stats
    data = json.load(f)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[2022-09-14 16:35:58,490] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=3_download_rocket_launches, task_id=print_stats, execution_date=20220914T163555, start_date=20220914T163558, end_date=20220914T163558
[2022-09-14 16:35:58,496] {standard_task_runner.py:97} ERROR - Failed to execute job 83 for task print_stats (Expecting value: line 2 column 1 (char 1); 645)
[2022-09-14 16:35:58,535] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-14 16:35:58,567] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
