[2022-09-14 14:31:10,453] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python scheduled__2022-09-09T00:00:00+00:00 [queued]>
[2022-09-14 14:31:10,462] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python scheduled__2022-09-09T00:00:00+00:00 [queued]>
[2022-09-14 14:31:10,463] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 14:31:10,464] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-14 14:31:10,465] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 14:31:10,479] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parser_python> on 2022-09-09 00:00:00+00:00
[2022-09-14 14:31:10,485] {standard_task_runner.py:52} INFO - Started process 166 to run task
[2022-09-14 14:31:10,489] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parser_dag', 'parser_python', 'scheduled__2022-09-09T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/pre_parser.py', '--cfg-path', '/tmp/tmprxlb2fbq', '--error-file', '/tmp/tmpg_953db_']
[2022-09-14 14:31:10,492] {standard_task_runner.py:80} INFO - Job 38: Subtask parser_python
[2022-09-14 14:31:10,533] {task_command.py:369} INFO - Running <TaskInstance: parser_dag.parser_python scheduled__2022-09-09T00:00:00+00:00 [running]> on host c0f73d32ee2c
[2022-09-14 14:31:10,603] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parser_dag
AIRFLOW_CTX_TASK_ID=parser_python
AIRFLOW_CTX_EXECUTION_DATE=2022-09-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-09T00:00:00+00:00
[2022-09-14 14:31:10,609] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pre_parser.py", line 91, in final
    data = parse_shop_list(city='moskva', shop_list=shop_list, page_range=100)
  File "/opt/airflow/dags/pre_parser.py", line 82, in parse_shop_list
    for shop in tqdm(shop_list):
NameError: name 'tqdm' is not defined
[2022-09-14 14:31:10,622] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parser_dag, task_id=parser_python, execution_date=20220909T000000, start_date=20220914T143110, end_date=20220914T143110
[2022-09-14 14:31:10,629] {standard_task_runner.py:97} ERROR - Failed to execute job 38 for task parser_python (name 'tqdm' is not defined; 166)
[2022-09-14 14:31:10,672] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-14 14:31:10,706] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
