[2022-09-14 18:47:24,835] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-09-14T18:47:23.846238+00:00 [queued]>
[2022-09-14 18:47:24,840] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-09-14T18:47:23.846238+00:00 [queued]>
[2022-09-14 18:47:24,841] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 18:47:24,842] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-14 18:47:24,843] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 18:47:24,851] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parser_python> on 2022-09-14 18:47:23.846238+00:00
[2022-09-14 18:47:24,859] {standard_task_runner.py:52} INFO - Started process 7053 to run task
[2022-09-14 18:47:24,866] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parser_dag', 'parser_python', 'manual__2022-09-14T18:47:23.846238+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/pre_parser.py', '--cfg-path', '/tmp/tmp9fbqgvfs', '--error-file', '/tmp/tmpk1j4_ckv']
[2022-09-14 18:47:24,867] {standard_task_runner.py:80} INFO - Job 84: Subtask parser_python
[2022-09-14 18:47:24,926] {task_command.py:369} INFO - Running <TaskInstance: parser_dag.parser_python manual__2022-09-14T18:47:23.846238+00:00 [running]> on host 1085bb4029c2
[2022-09-14 18:47:24,985] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parser_dag
AIRFLOW_CTX_TASK_ID=parser_python
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T18:47:23.846238+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T18:47:23.846238+00:00
[2022-09-14 18:47:24,989] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pre_parser.py", line 94, in final
    pathlib.Path(home_path).mkdir(parents=True, exist_ok=True)
NameError: name 'pathlib' is not defined
[2022-09-14 18:47:24,998] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parser_dag, task_id=parser_python, execution_date=20220914T184723, start_date=20220914T184724, end_date=20220914T184724
[2022-09-14 18:47:25,006] {standard_task_runner.py:97} ERROR - Failed to execute job 84 for task parser_python (name 'pathlib' is not defined; 7053)
[2022-09-14 18:47:25,042] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-14 18:47:25,068] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
